@startuml Student Identification
footbox off

participant Class as class
participant findStudentByName as fsbname
database "masterStudentList:Student[ ]" as msl
participant findStudentByNumber as fsbnumber
participant User as user


class -> fsbname : name:String
activate class

note left
    Class here refers to a function 
    or class that calls
    the findStudentByName function
end note

activate fsbname

    fsbname -> msl : name:String
    activate msl
    msl -> fsbname : students:Student[N]
    deactivate msl

alt N == 0

    fsbname -> class : null

else N == 1

    fsbname -> class : :Student

else N > 1

    fsbname -> fsbnumber : students:Student[N]
    activate fsbnumber

    fsbnumber -> user : promptForPhoneNumber():int
    activate user 
    user -> fsbnumber : number:int
    deactivate user

    alt number matches
        fsbnumber -> fsbname : :Student
        fsbname -> class : :Student

    else 
        fsbnumber -> fsbname : null
        deactivate fsbnumber 

        fsbname -> class : null
        deactivate fsbname
    end
        
end


deactivate class

@enduml