@startuml Student Identification
footbox off

participant InputParsing as fsbname
participant StudentList as msl

-> fsbname : findStudentByName()

activate fsbname

    fsbname -> msl : name:String
    activate msl
    msl --> fsbname : students:Student[N]
    deactivate msl

alt N == 0

    <-- fsbname : null

else N == 1

    <-- fsbname : :Student

else N > 1

    fsbname -> fsbname : students:Student[N]
    activate fsbname

    <- fsbname : promptForPhoneNumber():int
    -->  fsbname : number:int

    opt number matches
        fsbname --> fsbname : :Student
        <-- fsbname : :Student

    else 
        fsbname --> fsbname : null
        deactivate fsbname 

        <-- fsbname : null
        deactivate fsbname
    end
        
end

@enduml