package classify.commands;
//@@author tayponghee

import classify.student.Student;
import classify.student.StudentAttributes;
import org.junit.jupiter.api.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ListStudentsCommandTest {

    private static final String YIXIN = "Yi Xin";
    private static final String GERARD = "Gerard";

    /**
     * Test case to verify listing students with valid phone numbers.
     * This test checks if the method listStudentsWithPhoneNumbers(list)
     * correctly lists students with valid phone numbers.
     */
    @Test
    void testListStudentsWithValidNumbers() {
        ArrayList<Student> students = new ArrayList<>();
        Student student1 = new Student(YIXIN);
        StudentAttributes attributes1 = new StudentAttributes(student1);
        attributes1.setPhoneNumber(87654321);
        student1.setAttributes(attributes1);
        students.add(student1);

        ArrayList<String> expectedOutput = new ArrayList<>();
        expectedOutput.add("1." + YIXIN + " - Phone Number: 87654321");

        assertEquals(expectedOutput, captureOutput(() -> ListStudentsCommand.listStudentsWithPhoneNumbers(students)));
    }

    /**
     * Test case to verify listing students with invalid phone numbers.
     * This test checks if the method listStudentsWithPhoneNumbers(List)
     * correctly handles students with invalid phone numbers.
     */
    @Test
    void testListStudentsWithInvalidNumbers() {
        ArrayList<Student> students = new ArrayList<>();
        Student student1 = new Student(GERARD);
        StudentAttributes attributes1 = new StudentAttributes(student1);
        attributes1.setPhoneNumber(1234567);
        student1.setAttributes(attributes1);
        students.add(student1);

        ArrayList<String> expectedOutput = new ArrayList<>();
        expectedOutput.add("1." + GERARD + " - Invalid Phone Number! Save file may be corrupt.");
        
        assertEquals(expectedOutput, captureOutput(() -> ListStudentsCommand.listStudentsWithPhoneNumbers(students)));
    }

    /**
     * Captures the output generated by the given action.
     *
     * @param action The action whose output needs to be captured.
     * @return A list containing the captured output.
     */
    private List<String> captureOutput(Runnable action) {
        List<String> output = new ArrayList<>();
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        PrintStream printStream = new PrintStream(byteArrayOutputStream);
        PrintStream originalOut = System.out;
        System.setOut(printStream);

        action.run();

        System.out.flush();
        System.setOut(originalOut);
        output.add(byteArrayOutputStream.toString().trim());
        return output;
    }
}
