@startuml InputParsingSequenceDiagram

hide footbox


participant ":UserInput" as UI
participant ":InputParsing" as IP
participant ":Command" as commands 
participant "DataHandler" as fioc

-> UI : processInput(String)
activate UI
<- UI  : userCommand:String[ ]
deactivate UI

-> IP : parseUserCommand(userCommand:String[ ])
activate IP
IP -> commands : command to execute
activate commands
note over commands  
    this command class could refer to 
    AddStudent, EditStudent, or more
end note
commands -> fioc : update stored database
activate fioc
fioc --> commands
deactivate fioc
commands --> IP
deactivate commands
<-- IP
deactivate IP

@enduml

